# -*- coding: utf-8 -*-
"""Speech to Text convertor project

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OLZ4jesGocDO7l0dGO7Yx-5yPfzky27D
"""

DATASET_PATH = '/content/example.wav'

"""This details the path of the audio which is imported into the program. At the end, this audio will be converted into the text form."""

pip install speechrecognition

"""The pip function is used to install the speechrecognition software. It also collects and downloads packages for speechrecognition.

"""

#import library 
import speech_recognition as sr
#Initiаlize  reсоgnizer  сlаss  (fоr  reсоgnizing  the  sрeeсh)
r = sr.Recognizer()

"""Here, all the libraries and speech recognition module has been imported for the program to run"""

#import library
import speech_recognition as sr
#Initiаlize  reсоgnizer  сlаss  (fоr  reсоgnizing  the  sрeeсh)
r = sr.Recognizer()
# Reading Audio file as source
#  listening  the  аudiо  file  аnd  stоre  in  аudiо_text  vаriаble
with sr.AudioFile('example.wav') as source:
    audio_text = r.listen(source)
# recoginize_() method will throw a request error if the API is unreachable, hence using exception handling
    try:
        # using speechbrain 
        text = r.recognize_google(audio_text)
        print('Converting audio transcripts into text ...')
        print(text)
    except:
         print('Sorry.. run again...')

"""From the speech recognition module which uses the SpeechBrain module, we call the AudioFile  which accepts the audio file Friendly_Store.wav as an input. Using the SpeechBrain speech to text converter method, the audio file is converted into text form."""